### GET
GET http://127.0.0.1:3000
Content-Type: application/json

### POST ECOMMERCE
POST http://127.0.0.1:3000/api/ecommerce
Content-Type: application/json

{
    "UserEntreprenuer": "Lucia Pardo",
    "story": "Lucía, líder apasionada con más de 30 años de experiencia, enfrenta desafíos con determinación y perseverancia. Inspirada por la naturaleza, es un faro de esperanza para mujeres emprendedoras.",
    "brandName": "Achiras del Sagú",
    "whatSell": "Ofrecemos experiencias gastronómicas únicas con productos de sagú. Cada bocado es un viaje de sabores y texturas por los paisajes colombianos, uniendo tradición e innovación.",
    "howSell": "Nuestros productos artesanales reflejan pasión. Valoramos la calidad de las materias primas y empoderamos a mujeres, generando oportunidades de crecimiento.",
    "audienceTarget": "Nuestras Achiras son ideales para quienes buscan un snack saludable y sin gluten. Representan la diversidad gastronómica de Colombia, un regalo único para disfrutar en cualquier lugar.",
    "starProduct": "Achiras de Sagú rellenas de bocadillo",
    "starProductDescription": "Achiras: Un viaje culinario a la tradición colombiana sin gluten. Snack de sagú, crujiente y sabroso. Más que un snack, un tesoro cultural. Saludable, ideal para intolerantes al gluten. Lleva un pedacito de Colombia contigo.",
    "brandPersonality": "wise",
    "urlFacebook": "",
    "urlInstagram": "https://www.instagram.com/asoemaf_achiras?igsh=MWtraHE3enJxeTV4OQ==",
    "urlTiktokr": "",
    "urlGoogleMaps": ""
}

### POST CAMPAIGN
POST http://127.0.0.1:3000/api/campaign
Content-Type: application/json

{
    "campaignName": "chocotorta",
    "reason": "día de la madre",
    "location": "Bogotá D.C",
    "socialMedia": "Instagram",
    "contentType": "Foto"
}
### GET CAMPAIGN
GET http://127.0.0.1:3000/api/campaign
Content-Type: application/json

### GET:ID CAMPAIGN
GET http://127.0.0.1:3000/api/campaign/.....
Content-Type: application/json

### PATCH:ID CAMPAIGN
PATCH http://127.0.0.1:3000/api/campaign/.....
Content-Type: application/json

{
    "campaignName": "Heladeria",
    "reason": "día del padre",
    "location": "Cundinamarca",
    "socialMedia": "TikTok",
    "contentType": "Video"
}

### DELETE:ID CAMPAIGN
DELETE http://127.0.0.1:3000/api/campaign/.....
Content-Type: application/json